# Usage:
#
#     - uses: langston-barrett/ttlint/.github/actions/install-ttlint@SHA
#

name: Install ttlint
description: Install ttlint from GitHub Releases and add it to PATH
inputs:
  version:
    description: version (without the leading 'v')
    required: false
    default: '0.1.0'
  target:
    description: Target triple
    required: false
    default: 'x86_64-unknown-linux-gnu'
runs:
  using: composite
  steps:
    - name: Download and install ttlint
      shell: bash
      # For why `env`, see https://docs.zizmor.sh/audits/#template-injection
      env:
        REPO: langston-barrett/ttlint
        TARGET: ${{ inputs.target }}
        VERSION: ${{ inputs.version }}
      run: | # zizmor: ignore[github-env]
        set -euo pipefail
        install_dir="${HOME}/.local/bin"
        mkdir -p "${install_dir}"
        echo "${install_dir}" >> "${GITHUB_PATH}"
        name=${REPO#*/}
        file="${name}-${TARGET}.gz"
        url="https://github.com/${REPO}/releases/download/v${VERSION}/${file}"
        curl \
          --fail \
          --location \
          --proto '=https' \
          --retry 1 \
          --retry-delay 3 \
          --show-error \
          --silent \
          --tlsv1.2 \
          --output "${install_dir}/${name}.gz" \
          ${url}
        gunzip "${install_dir}/${name}.gz"
        chmod +x "${install_dir}/${name}"
